controller:
  image:
    tag: lts-jdk21
  servicePort: 80
  installPlugins:
    - kubernetes
    - git
    - blueocean
    - configuration-as-code
    - ws-cleanup
  jenkinsUrlProtocol: "http"
  serviceType: LoadBalancer
  JCasC:
    securityRealm: |-
      local:
        allowsSignup: false
        enableCaptcha: false
        users:
        - id: "admin"
          name: "Jenkins Admin"
          password: "admin"
  agentListenerEnabled: true
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 2Gi
agent:
  enabled: true
  containerCap: 1
  websocket: true
  podName: agent-smith
  alwaysPullImage: true
  customJenkinsLabels: [ "smith" ]
  image:
    repository: jenkins/inbound-agent
    tag: jdk21
  namespace: jenkins
  idleMinutes: 10
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 2Gi
