pipeline {
    agent {
        label 'smith'
    }

    stages {
        stage('Deploy') {
            environment {
                GOOGLE_PROJECT_ID = "gnutive"
                CLUSTER_NAME = "test-task-cluster"
            }
            steps {
                cleanWs()
                git branch: 'main', credentialsId: 'GitHub', url: 'git@github.com:dkhainas/gce-k8s-cicd.git'
                dir('webapp') {
                    sh './terraform init'
                    sh './terraform apply'
                }
            }
        }
    }
}
